# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # arkadi/freebsd images comes with sane defaults
  config.vm.guest = :freebsd
  config.vm.box = 'arkadi/freebsd-10.1-amd64'
  config.vm.box_version = "1.0"
  config.vm.hostname = "freebsd-base"
  # Stand up a private adapter for vagrant-winnfsd
  # config.vm.network "private_network", type: "dhcp"
  # No shared folder.  We're going to treat this as a remote machine
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # Virtualbox specific config
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.name = "freebsd-base"
  end
  # Shell provisioning because FreeBSD is a second class citizen when it comes
  # to vagrant-guest_ansible
  config.vm.provision "shell", path: "freebsd-ansible-guest.sh"
  # Now provision the guest itself via vagrant-guest_ansible
  config.vm.provision :guest_ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
