---
  # Tasks for deb-packages
- name: download deb packages
  action: get_url url={{item.value}} dest=/tmp/{{item.key}} mode=0700
  with_dict: "{{ development_vm.deb_packages | default({}) }}"
  when: development_vm.deb_packages is defined
- name: install deb packages
  action: apt deb=/tmp/{{item.key}} state=present
  with_dict: "{{ development_vm.deb_packages | default({}) }}"
  when: development_vm.deb_packages is defined
  tags:
    - deb-packages
