---
config:
  # Hostname the guest system will be known as on the network
  hostname: "PIT1V2SNM1-VM-IAS"
  # Virtualbox name for the VM
  vmname: "PIT1V2SNM1-VM-IAS"
  # Move SSH up to 22222 on the host, hopefully we avoid collisions up there 
  sshport: "22222"
  # Very important.  MAC address needs to be maintained between VM regenerations
  # for network access to lsvgnv0 and pitbpa1 resources
  publicmac: "0800273361B6"
  # publicmac: "auto"
