---
# Tasks for phpbrew
- name: install required apt packages
  action: apt pkg={{item}} state=present
  with_items: 
    - php5
    - php5-dev
    - php-pear
    - autoconf
    - automake
    - curl
    - build-essential
    - libxslt1-dev
    - re2c
    - libxml2
    - libxml2-dev
    - php5-cli
    - bison
    - libbz2-dev
    - libreadline-dev
    - libicu-dev
- name: get phpbrew
  action: get_url dest=/usr/bin/phpbrew url=https://github.com/phpbrew/phpbrew/raw/master/phpbrew
- name: set +x on phpbrew
  action: file path=/usr/bin/phpbrew mode=0755
- name: Initialize phpbrew
  action: shell phpbrew init
  args:
    creates: /home/{{development_vm.user.username | mandatory}}/.phpbrew
  become: yes
  become_user: "{{development_vm.user.username | mandatory}}"
  tags:
    - phpbrew
